# Generated by Django 5.2.3 on 2025-06-18 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_request', models.TextField(blank=True, null=True)),
                ('api_endpoint', models.URLField(blank=True, null=True)),
                ('faq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_answer', to='faq.faq')),
            ],
        ),
    ]
